# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'avatareeg_gui.ui'
#
# Created: Thu Mar  8 14:29:45 2012
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(854, 651)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo_label = QtGui.QLabel(self.centralwidget)
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap("avatar_logo_with_words_300pix.png"))
        self.logo_label.setObjectName("logo_label")
        self.verticalLayout.addWidget(self.logo_label)
        self.version_label = QtGui.QLabel(self.centralwidget)
        self.version_label.setObjectName("version_label")
        self.verticalLayout.addWidget(self.version_label)
        self.copyright_label = QtGui.QLabel(self.centralwidget)
        self.copyright_label.setObjectName("copyright_label")
        self.verticalLayout.addWidget(self.copyright_label)
        self.discoverCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.discoverCheckBox.setObjectName("discoverCheckBox")
        self.verticalLayout.addWidget(self.discoverCheckBox)
        self.csvCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.csvCheckBox.setObjectName("csvCheckBox")
        self.verticalLayout.addWidget(self.csvCheckBox)
        self.bdfCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.bdfCheckBox.setObjectName("bdfCheckBox")
        self.verticalLayout.addWidget(self.bdfCheckBox)
        self.setTimeButton = QtGui.QPushButton(self.centralwidget)
        self.setTimeButton.setMinimumSize(QtCore.QSize(100, 0))
        self.setTimeButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.setTimeButton.setObjectName("setTimeButton")
        self.verticalLayout.addWidget(self.setTimeButton)
        self.setInputShortButton = QtGui.QPushButton(self.centralwidget)
        self.setInputShortButton.setMinimumSize(QtCore.QSize(100, 0))
        self.setInputShortButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.setInputShortButton.setObjectName("setInputShortButton")
        self.verticalLayout.addWidget(self.setInputShortButton)
        self.setInputSquareWaveButton = QtGui.QPushButton(self.centralwidget)
        self.setInputSquareWaveButton.setMinimumSize(QtCore.QSize(100, 0))
        self.setInputSquareWaveButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.setInputSquareWaveButton.setObjectName("setInputSquareWaveButton")
        self.verticalLayout.addWidget(self.setInputSquareWaveButton)
        self.setInputElectrodesButton = QtGui.QPushButton(self.centralwidget)
        self.setInputElectrodesButton.setMinimumSize(QtCore.QSize(100, 0))
        self.setInputElectrodesButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.setInputElectrodesButton.setObjectName("setInputElectrodesButton")
        self.verticalLayout.addWidget(self.setInputElectrodesButton)
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(300, 250))
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.version_label.setText(QtGui.QApplication.translate("MainWindow", "Avatar EEG Driver version 0.xx", None, QtGui.QApplication.UnicodeUTF8))
        self.copyright_label.setText(QtGui.QApplication.translate("MainWindow", "Copyright (c) 2012 - Avatar EEG Solutions Inc.", None, QtGui.QApplication.UnicodeUTF8))
        self.discoverCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Discover Devices", None, QtGui.QApplication.UnicodeUTF8))
        self.csvCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Save to CSV file", None, QtGui.QApplication.UnicodeUTF8))
        self.bdfCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Save to BDF+ file", None, QtGui.QApplication.UnicodeUTF8))
        self.setTimeButton.setText(QtGui.QApplication.translate("MainWindow", "Set time", None, QtGui.QApplication.UnicodeUTF8))
        self.setInputShortButton.setText(QtGui.QApplication.translate("MainWindow", "Inputs to internal short", None, QtGui.QApplication.UnicodeUTF8))
        self.setInputSquareWaveButton.setText(QtGui.QApplication.translate("MainWindow", "Inputs to internal test signal", None, QtGui.QApplication.UnicodeUTF8))
        self.setInputElectrodesButton.setText(QtGui.QApplication.translate("MainWindow", "Inputs to normal (electrodes)", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Device", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Frames Saved", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Frames Lost", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Base Filename", None, QtGui.QApplication.UnicodeUTF8))

